# Batwing for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#1a1e22'
    foreground: '#c5ccd3'
    dim_foreground: '#b7bfc8'
    bright_foreground: '#e2e6e9'
  cursor:
    text: '#1a1e22'
    cursor: '#5ed6bc'
  vi_mode_cursor:
    text: '#1a1e22'
    cursor: '#5ed6bc'
  search:
    matches:
      foreground: '#374048'
      background: '#aea7fd'
    focused_match:
      foreground: '#aea7fd'
      background: '#374048'
    bar:
      foreground: '#374048'
      background: '#aea7fd'
  hints:
    start:
      foreground: '#374048'
      background: '#e8ce9b'
    end:
      foreground: '#e8ce9b'
      background: '#374048'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: '#c5ccd3'
    background: '#434d56'
  normal:
    black: '#647482'
    red: '#df8284'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#76a8f9'
    magenta: '#e397bb'
    cyan: '#83dde8'
    white: '#c5ccd3'
  bright:
    black: '#647482'
    red: '#df8284'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#76a8f9'
    magenta: '#e397bb'
    cyan: '#83dde8'
    white: '#c5ccd3'