# Batwing for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#21242b'
    foreground: '#c1c5cf'
    dim_foreground: '#b5bac6'
    bright_foreground: '#dadce2'
  cursor:
    text: '#21242b'
    cursor: '#60d8a9'
  vi_mode_cursor:
    text: '#21242b'
    cursor: '#60d8a9'
  search:
    matches:
      foreground: '#373c48'
      background: '#9d95f2'
    focused_match:
      foreground: '#9d95f2'
      background: '#373c48'
    bar:
      foreground: '#373c48'
      background: '#9d95f2'
  hints:
    start:
      foreground: '#373c48'
      background: '#e8ce9b'
    end:
      foreground: '#e8ce9b'
      background: '#373c48'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: '#c1c5cf'
    background: '#414754'
  normal:
    black: '#626b7e'
    red: '#df8284'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#75a8f9'
    magenta: '#e397bb'
    cyan: '#67c2cc'
    white: '#c1c5cf'
  bright:
    black: '#626b7e'
    red: '#df8284'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#75a8f9'
    magenta: '#e397bb'
    cyan: '#67c2cc'
    white: '#c1c5cf'