# Nightwing for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#14161f'
    foreground: '#c1c6d7'
    dim_foreground: '#b1b7cd'
    bright_foreground: '#e0e2eb'
  cursor:
    text: '#14161f'
    cursor: '#73cfdd'
  vi_mode_cursor:
    text: '#14161f'
    cursor: '#73cfdd'
  search:
    matches:
      foreground: '#282d3e'
      background: '#a293ff'
    focused_match:
      foreground: '#a293ff'
      background: '#282d3e'
    bar:
      foreground: '#282d3e'
      background: '#a293ff'
  hints:
    start:
      foreground: '#282d3e'
      background: '#e8ce9b'
    end:
      foreground: '#e8ce9b'
      background: '#282d3e'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: '#c1c6d7'
    background: '#3c435d'
  normal:
    black: '#464e6d'
    red: '#f4676a'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#88a2ff'
    magenta: '#e397bb'
    cyan: '#73cfdd'
    white: '#c1c6d7'
  bright:
    black: '#464e6d'
    red: '#f4676a'
    green: '#93c68c'
    yellow: '#e8ce9b'
    blue: '#88a2ff'
    magenta: '#e397bb'
    cyan: '#73cfdd'
    white: '#c1c6d7'
