#! /bin/fish
# ▄▄▄▄· .▄▄ ·  ▄▄▄·▄▄▌ ▐ ▄▌• ▌ ▄ ·. 
# ▐█ ▀█▪▐█ ▀. ▐█ ▄███· █▌▐█·██ ▐███▪
# ▐█▀▀█▄▄▀▀▀█▄ ██▀·██▪▐█▐▐▌▐█ ▌▐▌▐█·
# ██▄▪▐█▐█▄▪▐█▐█▪·•▐█▌██▐█▌██ ██▌▐█▌
# ·▀▀▀▀  ▀▀▀▀ .▀    ▀▀▀▀ ▀▪▀▀  █▪▀▀▀
# Created by: Jaden Wu
# Github: @jadnw
# Email: jadenwu137@protonmail.com

############################################################
### AUTOSTART
############################################################
# Keybindings Daemon
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
# Notification Daemon
dunst -conf $HOME/.config/dunst/dunstrc-x &
# Picom
picom --config $HOME/.config/picom/picom.conf &
# Fix default cursor
xsetroot -cursor_name left_ptr &
# Keyboard repeat rate/delay
xset r rate 300 40
# Set wallpaper
feh --bg-fill $HOME/.config/wallpapers/wallpaper.jpg &
# Panel
$HOME/.config/polybar/launch &

############################################################
### BSPWM
############################################################

### Rules
bspc monitor -d 1 2 3 4 5 6

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating focus=on
bspc rule -a pavucontrol state=floating focus=on
bspc rule -a btop state=floating focus=on

### Configs
bspc config focus_follows_pointer true
bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Colorscheme
$HOME/.config/bspwm/theme &
