#!/bin/fish

set theme ~/.config/rofi/x11/documents.rasi
set zathura_history_loc ~/.local/share/zathura/history 

killall -q rofi

set docs (cat ~/.local/share/zathura/history | grep -Po "\[\K[^\]]*" | grep "/home/")

set opt (printf "%s\n" $docs | rofi -x11 -dmenu -p "zathura" -theme $theme)

if test -z $opt
  exit 0
end

zathura $opt
exit 0
