#!/bin/fish

set theme $HOME/.config/rofi/x11/power.rasi
set uptime (uptime -p | sed -e 's/up //g')

# options
set logout ""
set lock ""
set suspend ""
set reboot ""
set shutdown ""

# variables passed to dmenu
set options "$logout\n$lock\n$suspend\n$reboot\n$shutdown"

set opt (echo -e $options | rofi -x11 -dmenu -p "Uptime: $uptime" -theme $theme)

if test -z $opt
  exit 0
end

switch $opt
  case $shutdown
    poweroff
  case $reboot
    reboot
  case $logout
    bspc quit
  case $lock
    betterlockscreen -l -w blur
  case $suspend
    systemctl suspend
end
