#!/bin/fish

set marker /tmp/waybar-dnd
set waiting (dunstctl count waiting)

function markup
  if test -e $marker
    echo '{ "text": "", "tooltip": "Do Not Disturb: ON", "class": "dnd" }'
  else if test $waiting -gt 0
    echo '{ "text": "", "tooltip": "You have new notification", "class": "notification" }'
  else
    echo '{ "text": "", "tooltip": "Do Not Disturb: OFF", "class": "none" }'
  end
end

function toggle-dnd
  if test -e $marker
    rm -f $marker; and pkill -SIGRTMIN+8 waybar
    dunstctl set-paused false
  else
    touch $marker; and pkill -SIGRTMIN+8 waybar
    dunstctl set-paused true
  end
end

switch $argv[1]
  case ''
    markup
  case toggle-dnd
    toggle-dnd
end
