#!/bin/fish

echo -e "Choose your tiling windows manager that you want to install?\n\t1 - RiverWM (Wayland)\n\t2 - SwayWM (Wayland)\n\t3 - HyprlandWM (Wayland)\n\t4 - BSPWM (X11)\n\t5 - RiverWM (Wayland) & BSPWM (X11)\n\t6 - SwayWM (Wayland) & BSPWM (X11)\n\t7 - Hyprland (Wayland) & BSPWM (X11)"
read -l -P "Your option? (default=1): " opt

sudo pacman -S --noconfirm --needed base-devel git fish rustup

# Install rustup toolchain
echo "Installing rustup with its stable toolchain ..."
rustup install stable
rustup default stable
echo "[DONE] Rustup installed."

sleep 1

# Install Paru
if which paru
  echo "[DONE] Paru detected."
else
  echo "Installing paru ..."
  git clone https://aur.archlinux.org/paru.git
  pushd paru
  makepkg -si --noconfirm
  popd
  rm -rf paru
  echo "[DONE] Paru installed."
end

sleep 1

echo "Refreshing repositories & Installing common packages with paru ..."
paru -Syy --noconfirm
paru -Sy --noconfirm archlinux-keyring

paru -S --noconfirm --needed \
  base-devel \
  btop \
  breeze-snow-cursor-theme \
  curl \
  docker \
  docker-compose \
  docker-machine \
  dunst \
  fd \
  fish \
  fnm-bin \
  git \
  go \
  golangci-lint \
  gtk3 \
  gtk4 \
  jq \
  librewolf-bin \
  luacheck \
  man \
  neovim \
  nnn \
  papirus-icon-theme \
  pdfjs \
  python-adblock \
  python-pip \
  qutebrowser \
  ripgrep \
  rofi-lbonn-wayland-git \
  rsync \
  rustup \
  sddm \
  sddm-sugar-candy-git \
  starship \
  stylua \
  tree \
  unzip \
  vscode \
  xdg-utils \
  xdg-user-dirs \
  zathura \
  zathura-pdf-poppler

echo "[DONE] Common packages has been installed"

sleep 1

# Enable systemd services
echo "Enabling services ..."
sudo systemctl enable sddm.service
echo "[DONE] System services enabled."

# SDDM
echo "Configuring SDDM.."
sudo rsync --recursive ./extras/sddm.conf.d /etc/
sudo rsync ./config/sddm-sugar-candy/theme.conf /usr/share/sddm/themes/sugar-candy/
echo "[DONE] SDDM configured."

sleep 1

# Fonts
echo "Downloading & copying fonts to directories ..."
rm -rf ~/.local/share/{themes,fonts}
mkdir -p ~/.local/share/{themes,fonts}
git clone https://github.com/jadnw/iosevka.git
rsync iosevka/patched/* ~/.local/share/fonts/
rm -rf iosevka
rsync ./fonts/local/* ~/.local/share/fonts/
sudo rsync --recursive ./fonts/system/* /usr/share/fonts/
fc-cache -r
echo "[DONE] Fonts copied to ~/.local/share/fonts & /usr/share/fonts."

# Run Docker with current user privileges
sudo usermod -aG docker $USER

sleep 1

echo "Copying configuration files to their locations ..."
# Copy common configs
rm -rf ~/.config
mkdir -p ~/.config
rsync --recursive ./config/{btop,dunst,fish,fontconfig,gtk-3.0,gtk-4.0,qutebrowser,rofi,zathura,starship.toml} ~/.config/
# Copy common extra configs
rsync ./extras/.gitconfig ~/
sudo rsync --recursive ./extras/reflector /etc/xdg/
echo "[DONE] Config files copied."

# Install GTK themes
echo "Downloading & copying Manhattan GTK themes"
git clone https://github.com/jadnw/manhattan.gtk.git
cp -R manhattan.gtk/themes/* ~/.local/share/themes/
rm -rf manhattan.gtk
echo "[DONE] GTK themes copied."

sleep 1

# Create a file to save installer metadata
set metadata_file ~/.config/jetdots.txt
rm -rf $metadata_file # for re-installing
touch $metadata_file

# Install one of tiling window managers [ riverwm (Wayland), swaywm (Wayland), bspwm (X11) ]
function install_river
  echo "riverwm" >> $metadata_file
  # Needed packages for Wayland (River)
  paru -S --noconfirm --needed \
    foot \
    glfw-wayland \
    grim \
    imagemagick \
    imv \
    qt5-wayland \
    qt6-wayland \
    river-git \
    slurp \
    swaybg \
    swayidle \
    swaylock-effects-git \
    waybar \
    wf-recorder \
    wlr-randr \
    wlsunset \
    wl-clipboard \
    xorg-xwayland \
    xorg-xlsclients
  
  # Copy Wayland configs to $HOME/.config/
  rsync --recursive ./config/{foot,river,imv,swaylock,waybar} ~/.config/
end

function install_sway
  echo "swaywm" >> $metadata_file
  # Needed packages for Wayland (Sway)
  paru -S --noconfirm --needed \
    foot \
    glfw-wayland \
    grim \
    imagemagick \
    imv \
    qt5-wayland \
    qt6-wayland \
    slurp \
    sway \
    swaybg \
    swaylock-effects-git \
    waybar \
    wf-recorder \
    wlr-randr \
    wlsunset \
    wl-clipboard \
    xorg-xwayland \
    xorg-xlsclients
  
  # Copy Wayland configs to $HOME/.config/
  rsync --recursive ./config/{foot,imv,sway,swaylock,waybar} ~/.config/
end

function install_hyprland
  echo "hyprlandwm" >> $metadata_file
  # Needed packages for Wayland (River)
  paru -S --noconfirm --needed \
    foot \
    glfw-wayland \
    grim \
    imagemagick \
    imv \
    qt5-wayland \
    qt6-wayland \
    slurp \
    swaybg \
    swayidle \
    swaylock-effects-git \
    waybar-experimental-git \
    wf-recorder \
    wlr-randr \
    wlsunset \
    wl-clipboard \
    xorg-xwayland \
    xorg-xlsclients
  
  # Copy executables
  curl -LO https://github.com/hyprwm/Hyprland/releases/download/v0.6.2beta/v0.6.2beta.tar.gz 
  mkdir hyprland && tar -xvzf v0.6.2beta.tar.gz -C ./hyprland
  sudo rsync ./hyprland/{hyprctl,Hyprland} /usr/bin
  sudo rsync ./hyprland/libwlroots.so.11032 /usr/lib/
  sudo mkdir -p /usr/share/wayland-sessions/
  sudo rsync ./hyprland/example/hyprland.desktop /usr/share/wayland-sessions/
  rm -rf hyprland
  # Copy Wayland configs to $HOME/.config/
  rsync --recursive ./config/{foot,river,imv,swaylock,waybar,hypr} ~/.config/
end

function install_bspwm
  echo "bspwm" >> $metadata_file
  # Needed packages for X11 (bspwm)
  paru -S --noconfirm --needed \
    alacritty \
    betterlockscreen \
    bspwm \
    feh \
    flameshot \
    picom-jonaburg-git \
    polybar \
    redshift \
    xclip \
    xf86-video-amdgpu \
    xorg-server \
    xorg-xrandr \
    xorg-xsetroot \
    xcolor \
    sxhkd
   
  # Copy X11 configurations to $HOME/.config/
  rsync --recursive ./config/{alacritty,bspwm,picom,polybar,betterlockscreenrc} ~/.config/

  # Extra configurations
   sudo rsync ./extras/xorg.conf.d/20-amdgpu.conf /etc/X11/xorg.conf.d/
  rsync --recursive ./extras/.icons ~/
end

# Choose a tiling windows manager
# You can completely install another WM by run this script again
echo "Installing your Tiling Window Managers ..."

switch $opt
case ''
install_river
  case 1
    install_river
  case 2
    install_sway
  case 3
    install_hyprland
  case 4
    install_bspwm
  case 5
    install_river
    install_bspwm
  case 6
    install_sway
    install_bspwm
  case 7
    install_hyprland
    install_bspwm
  case '*'
    echo "You donot want to install a tiling window manager. That's fine!"
    exit 1
end

echo "[DONE] Tiling Window Managers installed."

sleep 1

# Set greeting wallpaper
echo "Setting wallpapers ..."
mkdir -p ~/.config/wallpapers
rsync ./wallpapers/{wallpaper.jpg,lockscreen.jpg} ~/.config/wallpapers/
sudo rsync ./wallpapers/greeting.jpg /usr/share/sddm/themes/sugar-candy/
echo "[DONE] Wallpapers set."

# Install node
echo "Install Node v18 ..."
fnm install v18
echo "[DONE] Node installed."

# Install pylint
# python -m pip install pylint

# Remove build dependencies
echo "Removing build dependencies ..."
set i3_installed (paru -Qs i3-wm | grep "local/")
if test -n "$i3_installed"
  paru -Rns --noconfirm i3-wm
end

sleep 1

paru -Rns --noconfirm (paru -Qdtq)
echo "[DONE] Dependencies removed."

sleep 1
